//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCLINICAEntities : DbContext
    {
        public BDCLINICAEntities()
            : base("name=BDCLINICAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<T_BASE_FINANCIERA> T_BASE_FINANCIERA { get; set; }
        public DbSet<T_BASE_LEGAL> T_BASE_LEGAL { get; set; }
        public DbSet<T_BIEN> T_BIEN { get; set; }
        public DbSet<T_BITACORA_INCIDENCIA> T_BITACORA_INCIDENCIA { get; set; }
        public DbSet<T_COMPROBANTE> T_COMPROBANTE { get; set; }
        public DbSet<T_CONFIGURACION> T_CONFIGURACION { get; set; }
        public DbSet<T_EMPLEADO> T_EMPLEADO { get; set; }
        public DbSet<T_EMPRESA> T_EMPRESA { get; set; }
        public DbSet<T_EQUIPO_MEDICO> T_EQUIPO_MEDICO { get; set; }
        public DbSet<T_EQUIPO_USO> T_EQUIPO_USO { get; set; }
        public DbSet<T_ESPECIALIDAD_MEDICA> T_ESPECIALIDAD_MEDICA { get; set; }
        public DbSet<T_ESTRATEGIA_COMERCIAL> T_ESTRATEGIA_COMERCIAL { get; set; }
        public DbSet<T_INMUEBLE> T_INMUEBLE { get; set; }
        public DbSet<T_INVESTIGACION_COMERCIAL> T_INVESTIGACION_COMERCIAL { get; set; }
        public DbSet<T_MANTENIMIENTO_EQUIPO> T_MANTENIMIENTO_EQUIPO { get; set; }
        public DbSet<T_MODELO> T_MODELO { get; set; }
        public DbSet<T_MUEBLE> T_MUEBLE { get; set; }
        public DbSet<T_PACIENTE> T_PACIENTE { get; set; }
        public DbSet<T_PERSONA> T_PERSONA { get; set; }
        public DbSet<T_PLAN_DE_SALUD> T_PLAN_DE_SALUD { get; set; }
        public DbSet<T_PLAN_MANTENIMIENTO> T_PLAN_MANTENIMIENTO { get; set; }
        public DbSet<T_PLAN_PACIENTE> T_PLAN_PACIENTE { get; set; }
        public DbSet<T_PLAN_SERVICIO> T_PLAN_SERVICIO { get; set; }
        public DbSet<T_PROGRAMACION_MEDICA> T_PROGRAMACION_MEDICA { get; set; }
        public DbSet<T_PROYECTO_PLANSALUD> T_PROYECTO_PLANSALUD { get; set; }
        public DbSet<T_RESERVA_SERVICIO_SALUD> T_RESERVA_SERVICIO_SALUD { get; set; }
        public DbSet<T_SERVICIO_SALUD> T_SERVICIO_SALUD { get; set; }
        public DbSet<T_SOLICITUD_MANTENIMIENTO> T_SOLICITUD_MANTENIMIENTO { get; set; }
        public DbSet<T_TECNICO_MANTENIMIENTO> T_TECNICO_MANTENIMIENTO { get; set; }
        public DbSet<T_TIPO_PERSONA> T_TIPO_PERSONA { get; set; }
    }
}
