//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PLAN_DE_SALUD
    {
        public T_PLAN_DE_SALUD()
        {
            this.T_PLAN_PACIENTE = new HashSet<T_PLAN_PACIENTE>();
            this.T_PLAN_SERVICIO = new HashSet<T_PLAN_SERVICIO>();
            this.T_PROGRAMACION_MEDICA = new HashSet<T_PROGRAMACION_MEDICA>();
        }
    
        public int id_plan_salud { get; set; }
        public string nombre_plan { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public string objetivo { get; set; }
        public Nullable<int> id_investigacion_comercial { get; set; }
        public Nullable<int> id_estrategia_comercial { get; set; }
        public Nullable<int> id_base_financiera { get; set; }
        public Nullable<int> id_base_legal { get; set; }
        public Nullable<int> id_servicio { get; set; }
    
        public virtual T_BASE_FINANCIERA T_BASE_FINANCIERA { get; set; }
        public virtual T_BASE_LEGAL T_BASE_LEGAL { get; set; }
        public virtual T_ESTRATEGIA_COMERCIAL T_ESTRATEGIA_COMERCIAL { get; set; }
        public virtual T_INVESTIGACION_COMERCIAL T_INVESTIGACION_COMERCIAL { get; set; }
        public virtual ICollection<T_PLAN_PACIENTE> T_PLAN_PACIENTE { get; set; }
        public virtual ICollection<T_PLAN_SERVICIO> T_PLAN_SERVICIO { get; set; }
        public virtual ICollection<T_PROGRAMACION_MEDICA> T_PROGRAMACION_MEDICA { get; set; }
    }
}
