//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.TP2.WEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class T_PLAN_DE_SALUD
    {
        public T_PLAN_DE_SALUD()
        {
            this.T_PLAN_PACIENTE = new HashSet<T_PLAN_PACIENTE>();
            this.T_PLAN_SERVICIO = new HashSet<T_PLAN_SERVICIO>();
        }
        [Key]
        [Display(Name = "Id Plan")]
        public int id_plan_salud { get; set; }

        [Display(Name="Nombre Plan")]
        public string nombre_plan { get; set; }

        [Display(Name = "Descripcion")]
        [StringLength(30, ErrorMessage = "Campo permite entre {2} y {1} caracteres", MinimumLength=5)]
        public string descripcion { get; set; }

        [Display(Name = "Fecha Inicio")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString="{0:dd/MM/yyyy}", ApplyFormatInEditMode=false)]
        [Required(ErrorMessage="Debe ingresar {0}")]
        public Nullable<System.DateTime> fecha_inicio { get; set; }

        [Display(Name="Fecha Fin")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = false)]
        [Required(ErrorMessage = "Debe ingresar {0}")]
        public Nullable<System.DateTime> fecha_fin { get; set; }

        [Display(Name = "Objetivo")]
        public string objetivo { get; set; }

        public Nullable<int> id_investigacion_comercial { get; set; }
        public Nullable<int> id_estrategia_comercial { get; set; }
        public Nullable<int> id_base_financiera { get; set; }
        public Nullable<int> id_base_legal { get; set; }
        public Nullable<int> id_servicio { get; set; }
    
        public virtual T_BASE_FINANCIERA T_BASE_FINANCIERA { get; set; }
        public virtual T_BASE_LEGAL T_BASE_LEGAL { get; set; }
        public virtual T_ESTRATEGIA_COMERCIAL T_ESTRATEGIA_COMERCIAL { get; set; }
        public virtual T_INVESTIGACION_COMERCIAL T_INVESTIGACION_COMERCIAL { get; set; }
        public virtual ICollection<T_PLAN_PACIENTE> T_PLAN_PACIENTE { get; set; }
        public virtual ICollection<T_PLAN_SERVICIO> T_PLAN_SERVICIO { get; set; }
    }
}
